const uuid = require('uuid');

/*
Candy{
	_id:ObjectID,
	name:string,
	price: float,
	stock: int,
	rating: int,
	image: string(url),
	manufacturer: string,
	descrption: string,
	? ingredients: string,
	？Vegan: boolean,
	reviews: Array,
}
*/

/*
{
	_id: uuid.v4(),
	name: "",
	price: ,
	stock: ,
	rating: ,
    numRatings: ,
	image: "",
	manufacturer: "",
	descrption: "",
	ingredients: "",
    vegan: ,
	reviews: []
},
*/


const data = [
    {
        _id: uuid.v4(),
        name: "Airheads 60 Pack",
        price: 7.99,
        stock: 275,
        rating: 4.8,
        numRatings: 172,
        image: "https://m.media-amazon.com/images/I/91IT4i1CafL._SX679_.jpg",
        manufacturer: "Airheads",
        descrption: "Get crafty with your treats at playtime. Airheads are the chewy non-melting candy sure to satisfy any sweet tooth",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Atomic FireBall 60 pieces",
        price: 7.62,
        stock: 102,
        rating: 3.5,
        numRatings: 18,
        image: "https://m.media-amazon.com/images/I/81l58T47aHL._SX679_.jpg",
        manufacturer: "Ferrara Candy Company",
        descrption: "Atomic Fireballs are the original super-intense cinnamon candy. These mouth-igniting, sweat-inducing sweets give you a red-hot experience that keeps you coming back again and again. We dare you to eat as many candies as you can manage.",
        ingredients: "Sugar, Modified Cornstarch, Artificial Flavor, Carnauba Wax, Gum Arabic, Artificial Colors (Red 40 Lake).",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Bazooka Bubble Gum 1 pack",
        price: 2.79,
        stock: 384,
        rating: 4.3,
        numRatings: 78,
        image: 4.1,
        manufacturer: "Bazooka",
        descrption: "Join the fun with the 75th anniversary of America's iconic pink bubble gum brand, Bazooka Bubble Gum! Perfect chewy treat for kids and fun, nostalgic bubble gum for the whole family to enjoy. It's the perfect sweet and chewy treat this Easter!",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Hubba Bubba Gum 6 pack",
        price: 7.74,
        stock: 431,
        rating: 4.7,
        numRatings: 91,
        image: "https://m.media-amazon.com/images/I/814ixdzS2kL._SX679_PIbundle-6,TopRight,0,0_SX679SY647SH20_.jpg",
        manufacturer: "Wm. Wrigley Jr. Company",
        descrption: "Hubba Bubba Bubble Blast Bubble Gum—What's the biggest bubble you ever blew? Was it the size of a baseball? A grapefruit? What about a basketball? With the big bubble-gum flavor of Hubba Bubba, you'll find yourself getting plenty of practice blowing the biggest bubbles you can. Why not challenge your friends to a bubble-blowing competition? Have some fun with Hubba Bubba Bubble Gum.",
        ingredients: "Sugar, Gum Base, Corn Syrup, Glycerol; Less than 2% of: Natural and Artificial Flavors, Soy Lecithin, Acesulfame K, Aspartame, BHT (to Maintain Freshness), Colors (Red 40, Red 40 Lake).",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Candy Buttons 24 pack",
        price: 22.02,
        stock: 15,
        rating: 3.6,
        numRatings: 46,
        image: "https://m.media-amazon.com/images/I/81DeP58FbDL._SX679_PIbundle-24,TopRight,0,0_SX679SY545SH20_.jpg",
        manufacturer: "Cumberland Valley Company",
        descrption: "CLASSIC CANDY - 24 individual packages on the classic Candy Buttons. Great for parties, candy handouts, trick or treat, or a stroll down memory lane",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Candy Cigarettes 24 Case",
        price: 11.10,
        stock: 264,
        rating: 4.3,
        numRatings: 41,
        image: "https://m.media-amazon.com/images/I/91ycFEDr55L._SX679_.jpg",
        manufacturer: "World Confections Inc",
        descrption: "OK, now you're stirring up trouble. Candy cigarettes? Really? Yes, really. Live a little. Snack on a few of these tasty sugar sticks and enjoy the childhood flashbacks. Let them wash over you like your unfulfilled dreams or nostalgia over the loss of Blockbuster Video. Or, if you're too young for all of that, then buy a case, share â€˜em with friends, and mock the world we live in. Each case contains 24 .42 oz (12g) packs.",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Cnady Corn 11-oz",
        price: 4.05,
        stock: 419,
        rating: 4.7,
        numRatings: 52,
        image: "https://m.media-amazon.com/images/I/61HGYO9cDDL._SX679_PIbundle-3,TopRight,0,0_AA679SH20_.jpg",
        manufacturer: "Jelly Belly",
        descrption: "Classic candy corn at its best. Crème candy shaped like a kernel of corn, with a white tip, orange center, and a yellow base. It would be a shame to hide this candy treat, so pull out your candy dishes and fill them to the top with Brach's Classic Candy Corn",
        ingredients: "Sugar, Corn Syrup, Confectioner's Glaze, Salt, Dextrose, Gelatin, Sesame Oil, Artificial Flavor, Honey, Yellow 6, Yellow 5, Red 3.",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Candy Necklace 25 count",
        price: 14.99,
        stock: 464,
        rating: 4.5,
        numRatings: 140,
        image: "https://m.media-amazon.com/images/I/71hcXIMQCjL._SX679_.jpg",
        manufacturer: "Smarties Candy Co.",
        descrption: "Relive the days when the only thing more fun than eating candy was wearing it. This bulk candy bag contains 25 Smarties candy necklaces. Each necklace is individually wrapped and the bag is resealable for easy storage. Retro candy necklaces are a fun treat to share with friend and family at a birthday party, office party, costume party, tea party, Halloween party, school party, or Easter party. Fashionable and delicious, the candy necklaces make birthday gifts, Easter gifts, thank you gifts, and stocking stuffers as well as great for filling candy jars, Easter baskets, gift baskets, Halloween candy bags, and party favors. Old school candy is a great gift to give to older friends and family at Christmas, Easter, Valentine's Day, Thanksgiving, or Halloween. They're perfect for being able to take a little sweet snack with you to school, college, work, or while traveling. Whether you're five or fifty, wearable candy necklaces are a cute, retro fashion statement. They're a must have for those who love classic jewelry, clothes, fashion, and of course, candy.",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Dots Gumdrops 6.5oz 3 pack",
        price: 7.34,
        stock: 128,
        rating: 4.1,
        numRatings: 200,
        image: "https://m.media-amazon.com/images/I/61+LgOPagzL._SX679_PIbundle-3,TopRight,0,0_SX679SY437SH20_.jpg",
        manufacturer: "",
        descrption: "Dots original candy, assorted flavors, 6.5 ounce boxes (pack of 3) are chewy drops of assorted fruit flavor candy. A classic candy for generations.",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Dum Dums Pops 2 pack",
        price: 6.53,
        stock: 5,
        rating: 4.6,
        numRatings: 35,
        image: "https://m.media-amazon.com/images/I/71sIBp-yYVL._SX679_PIbundle-2,TopRight,0,0_AA679SH20_.jpg",
        manufacturer: "Spangler Candy",
        descrption: "the classic candy brand that makes things fun! Invented in 1924 and still popular today.  They're found in the homes of families across the U.S. and trusted by millions of small businesses who treat their customers with these delicious little pops.",
        ingredients: "Sugar, Corn Syrup, Citric Acid, Malic Acid, Salt, Artificial Flavor, Color Added (Includes Red 40, Yellow 6, Yellow 5, Blue 1).",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Gobstoppers 2 boxes",
        price: 10.29,
        stock: 275,
        rating: 4.6,
        numRatings: 153,
        image: "https://m.media-amazon.com/images/I/61Fj8rbFtIL.jpg",
        manufacturer: "",
        descrption: "Gobstoppers are truly everlasting and these delicious Jawbreakers, in a 5 Ounce Theater Style Box, will keep you satisfied for a lot longer than the average movie unless, of course, you are going to see Berlin Alexanderplatz which at 931 minutes is the world's longest film.        ",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Gumdrops 2.5 pounds",
        price: 13.69,
        stock: 67,
        rating: 4.4,
        numRatings: 159,
        image: "https://m.media-amazon.com/images/I/814nl0mCIFL._SX679_.jpg",
        manufacturer: "Tootsie Roll Industries",
        descrption: "Add some spice to your life with this light and colorful chewy mix! These gumdrops feature six unique flavors of cinnamon, clove, anise, spearmint, root beer (sassafras) and wintergreen.",
        ingredients: "Corn Syrup, Sucrose, Food Starch- Modified, Dextrose, Natural and Artificial Flavors, Red 40, Yellow 5, Blue 1. **Manufactured in a facility that also manufacture's products containing eggs.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Gummi Bears 5 pounds",
        price: 18.70,
        stock: 64,
        rating: 4.7,
        numRatings: 170,
        image: "https://m.media-amazon.com/images/I/51P-pDGMnGL.jpg",
        manufacturer: "Haribo",
        descrption: "Say hello to America's #1 Selling Gummi Bear! There’s no better companion than our original HARIBO GOLDBEARS, the delicious treat loved by young and old alike. HARIBO GOLDBEARS have been the gummi candy gold standard worldwide for over 90 years. Kids and grown-ups love it so, the happy world of HARIBO",
        ingredients: "Glucose Syrup (From Wheat or Corn), Sugar, Gelatin, Dextrose (From Wheat or Corn), Citric Acid, Corn Starch,Artificial and Natural Flavors, Palm Kernel Oil, Carnauba Wax, White Beeswax, Yellow Beeswax, Yellow 5, Red 40, Blue 1.",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Hershey's Kisses 35.8 oz bag",
        price: 10.98,
        stock: 205,
        rating: 4.8,
        numRatings: 60,
        image: "https://m.media-amazon.com/images/I/71EETs+VRnL._SX679_.jpg",
        manufacturer: "The Hershey Company",
        descrption: "Need to make sure the whole family is happy with the snack selection? Looking to keep your employees safe from hunger in the office? Whatever the case, HERSHEY'S KISSES candies have you covered. These milk chocolate classics make the perfect creamy treat throughout the day. Try some in a new dessert recipe or on top of your favorite cookie and cake treats for an extra bite of bliss your loved ones won't want to miss. Sprinkle a few over your homemade ice cream sundaes, or place them in party favors to delight guests with stunning foil wrappers and even more stunning flavor. These treats are perfect as stocking stuffers at Christmas, party favor filling during Valentine's Day, trick-or-treat candy at Halloween and basket sweets on Easter. Just don't forget to hang onto a few bite-size milk chocolates to include in your movie night snack selection and on-the-go trips. Try them chilled, on top of baked desserts and, of course, straight from the wrapper — any choice is a route straight to delicious!",
        ingredients: "Milk Chocolate (Sugar, Milk, Chocolate, Cocoa Butter, Milk Fat, Lecithin (Soy), Natural Flavor).",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: 'JawBreakers 1" 1.5lb ',
        price: 12.99,
        stock: 491,
        rating: 4,
        numRatings: 82,
        image: "https://m.media-amazon.com/images/I/8167kc4COFL._SX679_.jpg",
        manufacturer: "Ferrara Pan candy company",
        descrption: 'Jawbreakers - 1.5 lbs of 1" Fresh Delicious Multicolored Long Lasting Hard Sucking Candy',
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: 'Giant JawBreaker 3 3/8"',
        price: 19.98,
        stock: 173,
        rating: 4.5,
        numRatings: 87,
        image: "https://m.media-amazon.com/images/I/91n77pJps6L._SX679_.jpg",
        manufacturer: "Ferrara Pan candy company",
        descrption: "The World Famous Outrageously Humungeous Jawbreaker!!",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Jelly Belly Jelly Beans 3 lb",
        price: 21.95,
        stock: 214,
        rating: 4.6,
        numRatings: 192,
        image: "https://m.media-amazon.com/images/I/91ITzYWR4WL._SX569_.jpg",
        manufacturer: "Jelly Belly Candy Company",
        descrption: "Jelly beans are small bean-shaped sugar free candies with soft candy shells and thick gel interiors. The confection comes in a wide variety of colors and flavors, and is primarily made of little bit sugar.",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Jolly Ranchers 5 lb (360 pieces)",
        price: 13.19,
        stock: 466,
        rating: 4.8,
        numRatings: 186,
        image: "https://m.media-amazon.com/images/I/81bC8VDTGDL._SX679_.jpg",
        manufacturer: "The Hershey Company",
        descrption: "A mix of five fruity favorites for the whole family in just one bag of hard candy? You wouldn't have thought it possible if you didn't know JOLLY RANCHER candy. This 360-piece bag of individually wrapped fruit-flavored hard candy will keep each delicious piece fresh until it's time for a new bag. Featuring blue raspberry, green apple, cherry, grape and watermelon flavors, JOLLY RANCHER original hard candy offers a combination of the undisputed classics you know and love. Keep this convenient bulk bag with you on the go so you can share with friends, co-workers and family members throughout the day — but don't forget to save some for yourself during all that sharing! These fruit candies make the perfect candy bowl display all year thanks to vibrant colors and attractive JOLLY RANCHER wrappers. They're also great treats for holiday stockings, Easter baskets, Valentine's Day party favors and Halloween trick-or-treat bags. If you want a small candy with a big taste to keep your taste buds busy during movie nights, lunch breaks and snack breaks, JOLLY RANCHER hard candy is the treat for you.",
        ingredients: "Corn Syrup; Sugar; Contains 2% Or Less Of: Malic Acid; Natural Flavor And Artificial Flavor; Artificial Color [Red 40; Yellow 5; Blue 1; Yellow 6]; Mineral Oil; Lecithin (Soy)",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Junior Mints 3.5oz (4 pack)",
        price: 9.25,
        stock: 18,
        rating: 3.4,
        numRatings: 78,
        image: "https://m.media-amazon.com/images/I/51IsE4uBKgL._PIbundle-4,TopRight,0,0_SX500SY407SH20_.jpg",
        manufacturer: "Tootsie Roll Industries",
        descrption: "Junior Mints are a great pass-around treat, or quick way to keep a delicious snack on hand. Junior Mints, America's favorite chocolate covered creamy mint",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Laffy Taffy 145 count",
        price: 22.00,
        stock: 264,
        rating: 4.6,
        numRatings: 151,
        image: "https://m.media-amazon.com/images/I/918q2ejGSyL._SX679_.jpg",
        manufacturer: "Ferrara Candy Company",
        descrption: "Laffy Taffy candy: Sour Apple, Cherry, Strawberry & Bananas",
        ingredients: "CORN SYRUP, SUGAR, PALM OIL, AND LESSTHAN 2% OF MONO- ANDDIGLYCERIDES, HYDROGENATEDCOTTONSEED OIL, MALIC ACID, SALT,SOY LECITHIN, NATURAL FLAVORS,BLUE 1, RED 40, YELLOW 5. CONTAINS: SOY",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Life Savers 5 flavors 50 oz",
        price: 9.98,
        stock: 272,
        rating: 4.8,
        numRatings: 146,
        image: "https://m.media-amazon.com/images/I/61QlEQq9FhL._SX679_.jpg",
        manufacturer: "Mars, Incorporated",
        descrption: "Enjoy your favorite classic candy treat with LIFE SAVERS Original 5 Flavors Hard Candy. Featuring the famous cherry, raspberry, watermelon, orange, and pineapple fruit flavors, each bag contains enough hard candy pieces to share with friends, family or coworkers. The possibilities are endless with this party size bag filled with delicious, fruity LIFE SAVERS Hard Candy. Keep some LIFE SAVERS Hard Candy in your desk for an afternoon treat or fill piñatas and office candy dishes with these individually wrapped fruit-flavored candies.",
        ingredients: "Sugar, Corn Syrup, High Fructose Corn Syrup, Citric Acid, Natural and Artificial Flavors, Colors (Red 40, Yellow 5, Blue 1).",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Life Savers Mints 50 oz (2 packs)",
        price: 15.80,
        stock: 312,
        rating: 4.9,
        numRatings: 184,
        image: "https://m.media-amazon.com/images/I/71itiiLETHL._SX679_.jpg",
        manufacturer: "Mars, Incorporated",
        descrption: "Enjoy your favorite classic minty treat when you purchase Life savers Mints Wint-O- Green Hard Candy. Originally debuting in 1935, this iconic minty flavor has stood the test of time. This classic American candy was designed to resemble a life preserver. Each individually wrapped mint is packed with refreshing wintergreen flavor to help keep you feeling fresh. Each bulk candy bag contains enough mints to share in a candy dish at home or at the office. Guests will love to find their favorite mint!",
        ingredients: "Made of: Sugar, Corn Syrup, Artificial Flavor, Stearic Acid.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "M&M's 62 oz Jar",
        price: 11.21,
        stock: 23,
        rating: 4.7,
        numRatings: 126,
        image: "https://m.media-amazon.com/images/I/71Vi6+kR0hL._SX679_.jpg",
        manufacturer: "Mars Chocolate",
        descrption: "M&M's (stylized as m&m's) are multi-colored button-shaped chocolates, each of which has the letter 'm' printed in lower case in white on one side, consisting of a candy shell surrounding a filling which varies depending upon the variety of M&M's.",
        ingredients: "CHOCOLATE",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Mike and Ike 54 oz",
        price: 9.89,
        stock: 40,
        rating: 4.6,
        numRatings: 132,
        image: "https://m.media-amazon.com/images/I/41R2VkHI5sL.jpg",
        manufacturer: "Just Born Quality Confections",
        descrption: "With MIKE AND IKE Original Fruits, you can experience great-tasting fruity, chewy candy exploding with five assorted fruit flavors including fan favorites like Cherry, Lemon, Lime, Orange and Strawberry. It's fruity, it's chewy, it's FRUCHEWY! Classic MIKE AND IKE Original Fruits have been loved by fans for over 80 years and is THE perfect candy to enjoy at home while streaming your favorite movie or online gaming. Stock up now with this convenient TWELVE (12) pack of your favorite candy. Then, throw a box of 5 ounce MIKE AND IKE Original Fruits in a daypack for when you need that fruity flavor pick-me-up! Did you know? MIKE AND IKE Original Fruits is fat free, gluten free and kosher! Don’t forget to keep up-to-date with your favorite candy by following us on Facebook, Instagram and twitter. For the latest nutrition and ingredient information we recommend referencing the product label or call 1-888-MIKEIKE.",
        ingredients: "SUGAR, CORN SYRUP, MODIFIED FOOD STARCH, CONTAINS LESS THAN 0.5% OF THE FOLLOWING: CITRIC ACID, MALIC ACID, FUMARIC ACID, SODIUM CITRATE, NATURAL AND ARTIFICIAL FLAVORS, DEXTRIN, CONFECTIONERS GLAZE, CARNAUBA WAX, MEDIUM CHAIN TRIGLYCERIDES, RED #40, YELLOW #6, YELLOW #5 (TARTRAZINE), BLUE #1.",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Nerds 141g (6 pack)",
        price: 12.23,
        stock: 11,
        rating: 4.7,
        numRatings: 94,
        image: "https://m.media-amazon.com/images/I/51AMy3pJnFL._PIbundle-6,TopRight,0,0_SX500SY332SH20_.jpg",
        manufacturer: "Willy Wonka Candy Factory",
        descrption: "Tiny, tangy, crunchy candy, Nerds are delicious little characters—small and peculiarly shaped yet lovably packed with taste. Nerds couples two complementary flavors in its iconic box designed with dual chambers. Putting true delicious flavors side by side, Nerds lets candy lovers pour out petite pieces of pure delight.",
        ingredients: "DEXTROSE, SUGAR, MALIC ACID, 2% OR LESS OF CORN SYRUP, NATURAL FLAVORS, CARNAUBA WAX, CARMINE COLOR, COLOR ADDED, BLUE 1 LAKE, BLUE 2 LAKE, RED 40 LAKE.",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Marshmallow Peeps 2 Pack",
        price: 6.50,
        stock: 196,
        rating: 4.6,
        numRatings: 96,
        image: "https://images-na.ssl-images-amazon.com/images/I/41m5oeGtC5L._SY300_SX300_QL70_FMwebp_.jpg",
        manufacturer: "Just Born Quality Confections",
        descrption: "Marshmallow Peeps Bunnies are the perfect addition to Easter baskets. Peeps are dearly beloved for their famously fluffy marshmallow and sugary feel.",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "PEZ 11 oz Bag",
        price: 6.19,
        stock: 108,
        rating: 4.6,
        numRatings: 18,
        image: "https://m.media-amazon.com/images/I/81BPXGwNpIL._SX679_PIbundle-35,TopRight,0,0_AA679SH20_.jpg",
        manufacturer: "the Haas family",
        descrption: "PEZ Candy Refill Rolls, 11 oz Variety Bag (approx 35 Full Rolls in a bag)",
        ingredients: "Sugar, Corn Syrup, Adipic Acid, Hydrogenated Palm Kernel & Palm Oil, Mono & Diglycerides, Natural & Artificial Flavors, Artificial Colors FD&C Red 3, Yellow 5, Yellow 6, Blue 2.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Pixy Stix 3.2 oz (3 pack)",
        price: 7.19,
        stock: 249,
        rating: 4.8,
        numRatings: 186,
        image: "https://m.media-amazon.com/images/I/71gx-gxkmgL._SX679_PIbundle-3,TopRight,0,0_AA679SH20_.jpg",
        manufacturer: "Ferrara Candy Company",
        descrption: "Straws filled with powdered bliss. Enjoy a mix of grape, cherry, orange, and Maui punch flavors. Pixy Stix elates the tastes with classic sweet and tangy flavor in a pourable straw container. Pixy Stix delivers a delicious fruity sensation with a dash of tart that sets this classic apart. Perfect for games, Halloween, and parties.",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Pocky Sticks 2.47 Oz",
        price: 2.69,
        stock: 225,
        rating: 4.8,
        numRatings: 154,
        image: "https://m.media-amazon.com/images/I/717X+SQ4a8L._SX679_.jpg",
        manufacturer: "Ezaki Glico USA Co., Ltd.",
        descrption: "Did you know that Pocky is the most popular chocolate covered biscuit in Japan? Pocky is made from expertly crafted biscuit dough that uses the highest quality flour, and a chocolate coating using Cacao grown under the Ecuadorian sun. Combine these with an easy-to-handle stick that keeps chocolate off of your hands, and you've got the ultimate in snacking heaven. With plenty of sticks in each box, Pocky is about sharing happiness with friends, family, co-workers--anyone, anytime, anywhere! Just open a box, pass it around, and watch the smiles and happiness spread.",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Pop Rocks 12 Pack",
        price: 9.54,
        stock: 237,
        rating: 4.4,
        numRatings: 37,
        image: "https://s7.orientaltrading.com/is/image/OrientalTrading/VIEWER_ZOOM/pop-rocks-hard-candy-12-pc-~k289",
        manufacturer: "Zeta Espacial S.A.",
        descrption: "TASTE THE EXPLOSION - Pop Rocks takes candy eating to the next level with its popping sensation and fizzing and crackling sounds!",
        ingredients: "Pop rocks: sugar, lactose (milk), corn syrup, artificial flavor, colors (red 40, blue 1, yellow 5 (tartrazine)) processed with carbon dioxide",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Reese's Peanut Butter Cups 33 oz (60 Pieces)",
        price: 10.98,
        stock: 218,
        rating: 4.8,
        numRatings: 476,
        image: "https://m.media-amazon.com/images/I/818ah-IMyWS._SX679_.jpg",
        manufacturer: "The Hershey Company",
        descrption: "Don't let their small size fool you: REESE'S Milk Chocolate Peanut Butter Snack Size Cups Candies are huge on chocolate and peanut butter taste! Individually wrapped, bite-sized and perfectly poppable, REESE'S Candies make a delicious anytime treat. Plus, this bulk bag ensures you'll have plenty for sharing with friends and family during all your get-togethers! You can even have this giant pack tag along with you as you take on a road trip, if need a pick me up at the office or want to share some time with your loved ones at home. All you have to do is unwrap these chocolate peanut butter delights and enjoy! If you want to get more creative, add these snack-size peanut butter treats covered in milk chocolate to your ice cream sundae buffet or place them on individually knotted pretzels to melt in the oven for a sweet, salty and gooey sensation. At the end of the day, REESE'S Milk Chocolate Peanut Butter sweets are a timeless indulgence that are kosher and gluten free for when you need a quick treat. They make scrumptious holiday treats, too whether you hide them in Easter baskets and inside stockings or gift the entire bag during Valentine's day and use them for dessert decorations at Halloween.",
        ingredients: "MILK CHOCOLATE [SUGAR; COCOA BUTTER; CHOCOLATE; SKIM MILK; MILK FAT; LACTOSE; LECITHIN (SOY); PGPR]; PEANUTS; SUGAR; DEXTROSE; SALT; TBHQ AND CITRIC ACID, TO MAINTAIN FRESHNESS",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Reese's Pieces 48 oz Bag",
        price: 9.99,
        stock: 463,
        rating: 4.8,
        numRatings: 195,
        image: "https://m.media-amazon.com/images/I/71X7wI1iqLL._SX679_.jpg",
        manufacturer: "The Hershey Company",
        descrption: "REESE'S PIECES peanut butter candy is the classic candy you've always loved. Imagine taking the classically loved REESE'S peanut butter and smashing it down into tiny pieces of goodness. And don't forget to cover them with colorful hard candy. Savor the taste of creamy peanut butter surrounded by a sweet and crunchy candy shell. These candy pieces are gluten free and kosher. There's just something about the sound of pouring REESE'S PIECES sweets into your hand during your favorite movie or grabbing some as you walk out the door. Speaking of, keep your candy bowls filled with crunchy, delicious REESE'S PIECES peanut butter candy for easy access. Your friends and family will empty the candy dish as fast as you can fill it! You can also sprinkle these peanut butter candies over your ice cream or decorate a birthday cake with a unique design. Any sweet treat you bake is the right dessert for this crunchy peanut butter candy. Think cookies, brownies, cupcakes and caramel bars. This bag of candy is resealable for lasting freshness and snacking on the go.",
        ingredients: "SUGAR; PARTIALLY DEFATTED PEANUTS; HYDROGENATED VEGETABLE OIL [PALM KERNEL OIL; SOYBEAN OIL]; CORN SYRUP SOLIDS; DEXTROSE; CONTAINS 2% OR LESS OF: CORN SYRUP; PALM KERNEL OIL; SALT; CONFECTIONER'S GLAZE; MODIFIED CORNSTARCH; LECITHIN (SOY); ARTIFICIAL COLOR [YELLOW 6 LAKE; YELLOW 5 LAKE; RED 40 LAKE; BLUE 1 LAKE]; VANILLIN, ARTIFICIAL FLAVOR; CARNAUBA WAX; MILK",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Ring Pop 20 Count Bag",
        price: 6.98,
        stock: 35,
        rating: 4.7,
        numRatings: 53,
        image: "https://m.media-amazon.com/images/I/91eiAEgD4yL._SX679_.jpg",
        manufacturer: "Topps",
        descrption: "Ring POP is the ultimate iconic wearable lollipop with an enormous eye-catching candy gem that tastes as good as it looks. Slip it on your finger and enjoy the flavoring the attention! each bag includes 20 0.5 oz individually-wrapped Ring POP lollipops in a selection of 6 assorted flavors - Strawberry, blue Raspberry, rainbow Sherbert freeze, sour Cherry, Watermelon and berry Blast. Ring POP lollipops are the perfect accessory for kids and the perfect treat for any birthday party, party favor, Wedding, engagements, bachelorette Party, Bridal shower, baby shower, graduation and any other celebration! proudly made in the USA. Disclaimer: Not for children 3 and under.",
        ingredients: "",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Skittles 50 oz Bag",
        price: 10.28,
        stock: 360,
        rating: 4.8,
        numRatings: 295,
        image: "https://m.media-amazon.com/images/I/61knPWtpSLL._SX679_.jpg",
        manufacturer: "Mars, Incorporated",
        descrption: "Share the rainbow when you stock up on party size bags of SKITTLES Original Fruity Candy. Every 50-ounce bag of SKITTLES Candy is filled with fruity flavor, including strawberry, orange, grape, lemon and lime. Each bag comes packed with enough candy to share with friends, family or coworkers. Stock the office pantry with a candy treat everyone will love. TASTE THE RAINBOW.",
        ingredients: "SUGAR, CORN SYRUP, HYDROGENATED PALM KERNEL OIL, LESS THAN 2% OF: CITRIC ACID, TAPIOCA DEXTRIN, MODIFIED CORN STARCH, NATURAL AND ARTIFICIAL FLAVORS, COLORS (TITANIUM DIOXIDE, RED 40 LAKE, YELLOW 5 LAKE, YELLOW 6 LAKE, BLUE 2 LAKE, BLUE 1, BLUE 1 LAKE, YELLOW 5, YELLOW 6, RED 40), SODIUM CITRATE, CARNAUBA WAX.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Smarties Candy Rolls 5 Pound Bag",
        price: 14.99,
        stock: 251,
        rating: 4.8,
        numRatings: 117,
        image: "https://m.media-amazon.com/images/I/71ypakLMbOL._SX679_.jpg",
        manufacturer: "Nestlé",
        descrption: "Smarties: Indulge your sweet tooth with the yummy Smarties candy wafer roll you know and love, just the way you remember it. It's no wonder they have been one of the leading Halloween treats for over 50 years. We manufacture six colors of candy tablets that are randomly mixed together; Orange/Cream, Pineapple, Cherry Strawberry, Grape, and Orange; The perfect treat anytime, anywhere. From our classic wafers to crave worthy new flavors, sours, tropicals, mega lollies, candy money, and more, there’s a Smarties treat for everyone.",
        ingredients: "DEXTROSE, CITRIC ACID, CALCIUM STEARATE, NATURAL AND ARTIFICIAL FLAVOR, COLORS (RED 40 LAKE, YELLOW 5 LAKE, YELLOW 6 LAKE, BLUE 2 LAKE)",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Sour Patch Kids 28.8 oz Bag",
        price: 8.68,
        stock: 89,
        rating: 4.6,
        numRatings: 150,
        image: "https://m.media-amazon.com/images/I/91SjBdeLx7L._SX679_.jpg",
        manufacturer: "Mondelēz International, Inc.",
        descrption: "BIG SOUR PATCH KIDS candy are mischief-filled sour-then-sweet treats. Soft, chewy, and oh so fun, these tasty candies are 2x bigger than the original and come in playful fruity flavors to help you escape the everydayness of your day. Sour. Sweet. Gone. SOUR PATCH KIDS candy is essential for holidays, parties, and everyday snacking. Fill treat jars, Easter baskets, and goodie bags; delight trick-or-treaters during Halloween and little ones at the movies; and complete stocking stuffers, care packages, and advent calendars with this playful confection. SOUR PATCH KIDS candy make every day sweeter.",
        ingredients: "SUGAR, INVERT SUGAR, CORN SYRUP, MODIFIED CORN STARCH, TARTARIC ACID, CITRIC ACID, NATURAL AND ARTIFICIAL FLAVOR, YELLOW 6, RED 40, YELLOW 5, BLUE 1.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "StarBursts 36 Pack",
        price: 27.99,
        stock: 196,
        rating: 4.8,
        numRatings: 158,
        image: "https://m.media-amazon.com/images/I/61JaX+qsGnL._SX679_.jpg",
        manufacturer: "The Wrigley Company",
        descrption: "Experience the EXTRAordinary juiciness of STARBURST Fruit Chews. With 36 singles size packs of STARBURST Original Candy in every box, there's plenty of fruity, chewy fun for everyone. Featuring the original STARBURST Candy flavors that started it all: strawberry, cherry, orange and lemon flavors. This bulk candy package is great for stocking concession stands, vending machines or the office pantry. From STARBURST candies right out of the wrapper to STARBURST recipes and decorations, there are endless ways to add a burst of juicy flavor every day.",
        ingredients: "Made of: Corn Syrup, Sugar, Hydrogenated Palm Kernel Oil, Apple Juice from Concentrate, Less than 2%- Citric Acid, Dextrin, Gelatin, Food Starch-Modified, Artificial and Natural Flavors, Ascorbic Acid (Vitamin C), Coloring (Red 40, Blue 1).",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Swedish Fish 5 oz Bag",
        price: 3.78,
        stock: 188,
        rating: 4.3,
        numRatings: 23,
        image: "https://m.media-amazon.com/images/I/81FSEGWB5LL._SX679_.jpg",
        manufacturer: "Cadbury Adams",
        descrption: "The #1 Fish-Shaped Candy in the World SWEDISH FISH candy aren’t regular fish. For one, they taste like fruit, not fish. For another, they’re always up for a flipping good time! Everyone agrees they’re quite the catch. (A good fish pun goes over swimmingly with this school.) The Coolest Fish in the Sea SWEDISH FISH candy are soft, chewy, and oh so delicious. And they love the same things you do! Movies, holidays, party favors, treat jars, goodie baskets, gift bags, Easter baskets, stocking stuffers, care packages, trick-or-treating—SWEDISH FISH never scale back on fun. Add this package of SWEDISH FISH Original Flavor Candy to your cart for fun, fruity treats.",
        ingredients: "SUGAR, INVERT SUGAR, CORN SYRUP, MODIFIED CORN STARCH, CONTAINS LESS THAN 2% OF CITRIC ACID, WHITE MINERAL OIL, NATURAL AND ARTIFICIAL FLAVOR, RED 40, CARNAUBA WAX",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Sweetarts 5 oz Box",
        price: 5.30,
        stock: 360,
        rating: 4.7,
        numRatings: 193,
        image: "https://m.media-amazon.com/images/I/61h4UHHVGtL._SX679_.jpg",
        manufacturer: "Willy Wonka Candy Company",
        descrption: "A pioneer in taste innovation, Sweet ARTS delivers the original flavor combination of delightfully sweet and delicately tart in an array of colorful candy creations. Original Sweet ARTS unleashes its magic by compressing this one of a kind taste into delicious, bite-sized candies. Original Sweet ARTS can be chewed to a yummy crumble or dissolved to savor the tantalizingly tangy sensation that has become a sentimental favorite.",
        ingredients: "DEXTROSE, MALTODEXTRIN, MALIC ACID (DL-MALIC ACID), 2% OR LESS OF CALCIUM STEARATE, NATURAL FLAVORS, BLUE 1 LAKE, BLUE 2 LAKE, RED 40 LAKE, YELLOW 5 LAKE.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Tootsie Pops 100 count",
        price: 11.98,
        stock: 442,
        rating: 4.7,
        numRatings: 112,
        image: "https://m.media-amazon.com/images/I/71ToYmulsXL._SX679_.jpg",
        manufacturer: "Tootsie Roll Industries",
        descrption: "Tootsie Pops -- The world’s number 1-selling candy-filled lollipop. The chewy, Tootsie Roll center; covered with a delicious, hard candy coating; is a wonderfully delicious treat. A Tootsie original that was the first lollipop to provide a hidden candy “prize.” Tootsie Pops are known and loved by adults and kids around the world; and the mystery of how many licks it takes to get to the Tootsie Roll center of a Tootsie Pop still remains unsolved.",
        ingredients: "",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Tootsie Roll 700 count",
        price: 15.50,
        stock: 14,
        rating: 4.8,
        numRatings: 157,
        image: "https://m.media-amazon.com/images/I/813jbew2-AL._SX679_.jpg",
        manufacturer: "Tootsie Roll Industries",
        descrption: "700 Individually wrapped Tootsie Roll Midgees per bag",
        ingredients: "Sugar, Corn Syrup, Partially Hydrogenated Soybean Oil, Condensed Skim Milk, Cocoa, Whey, Soya Lecithin, Artifical & Natural Flavors",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Twizzlers 2.5 oz Bags (18 Count)",
        price: 18.00,
        stock: 276,
        rating: 4.7,
        numRatings: 128,
        image: "https://m.media-amazon.com/images/I/71Cv8SxjYFS._SX679_.jpg",
        manufacturer: "The Hershey Company",
        descrption: "There ain't no party like a TWIZZLERS party! Seriously though, TWIZZLERS Twists strawberry-flavored chewy candies are too fun not to enjoy at every movie marathon, birthday party and tailgate. With a bag of strawberry-flavored chewy candies ready for action, bite off both ends of the Twists candy to create a straw. Dip your straw into a cold glass of milk, hot chocolate and milkshake (maybe not all at once) or slurp up the whipped topping on your ice cream sundae. If you're more into eating a couple of these chewy treats straight from the bag, you're ready to go. Keep your pantry stocked with low-fat and kosher TWIZZLERS Twists candy, stash some in your work desk, take the bag on a road trip or bring a pack to your next party gathering. For a unique twist on these already fun TWIZZLERS candies, melt several white or milk chocolate bars and dip in your goodies. Afterward, cover the candy in sprinkles and let the new treats cool! They also make great snacks for sharing during the holidays.",
        ingredients: "CORN SYRUP; ENRICHED WHEAT FLOUR (FLOUR, NIACIN, FERROUS SULFATE, THIAMIN MONONITRATE, RIBOFLAVIN, AND FOLIC ACID); SUGAR; CORNSTARCH; CONTAINS 2% OR LESS OF: PALM OIL; SALT; ARTIFICIAL FLAVOR; MONO AND DIGLYCERIDES; CITRIC ACID; POTASSIUM SORBATE (PRESERVATIVE); ARTIFICIAL COLOR (RED 40); MINERAL OIL; LECITHIN (SOY); GLYCERIN.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Warheads Extreme Sour 25 oz (175 Piece)",
        price: 12.83,
        stock: 401,
        rating: 4.5,
        numRatings: 87,
        image: "https://m.media-amazon.com/images/I/91A5NPmZuVL._SX679_.jpg",
        manufacturer: "Impact Confections",
        descrption: "Warheads Sour Candy has earned a reputation for position among the sourest candies out there. Each mouthful joins sweet and sour to provide you with a bit of both, but with more intensity than most candies. The first Warhead was made in 1975 in Taiwan. Once it got here it caught on quickly among candies fans of all ages, particularly those who craved something more extreme. While classic Warheads are enough for some, others are ready to take things to the next level. That's where Warheads Extreme Sours comes in! Our bulk Warheads Extreme Sours package includes multiple pounds of individually wrapped bits that are suitable for parties, picnics, and events!",
        ingredients: "Corn Syrup, Sugar, Microencapsulated Malic Acid (Malic Acid, Hydrogenated Palm Oil), Citric Acid, Gum Acacia, Soybean Oil (Processing Aid), Ascorbic Acid, Artificial Flavors, Carnauba Wax, Corn Starch, Blue 1, Red 40, Yellow 5.",
        vegan: true,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "Whoppers 5 oz Box (12 Count)",
        price: 14.88,
        stock: 278,
        rating: 4.4,
        numRatings: 104,
        image: "https://m.media-amazon.com/images/I/81fKwsSQv-L._SX679_PIbundle-12,TopRight,0,0_AA679SH20_.jpg",
        manufacturer: "The Hershey Company",
        descrption: "WHOPPERS original malted milk balls candy is the classic chocolate candy everyone wants to munch on during movie nights and snack breaks. This malted treat is coated in rich chocolate candy that makes for a decadent taste and a satisfying crunch. Keep a box in your kitchen pantry or desk drawer to make sure you always have a sweet treat on hand. These bite-size candy pieces are a classic movie night staple ready to fill out the snack selection and make your next film adventure extra special. Looking for more possibilities? Try adding these treats to your favorite cookie or brownie recipes. Bring a box to work to share with co-workers and friends, and leave a few at home for family members and guests. If you'd like to up your snacking and gifting games, try stuffing holiday stockings, Easter baskets, Valentine's Day gift bags or Halloween party favors with full boxes of WHOPPERS malted milk candy. Wherever these delectable treats end up, someone is sure to enjoy them to the last piece!",
        ingredients: "SUGAR; CORN SYRUP SOLIDS; WHEY (MILK); HYDROGENATED PALM KERNEL OIL; PALM KERNEL OIL; CORN SYRUP; COCOA; MALTED MILK [BARLEY MALT; WHEAT FLOUR; MILK; SALT; BAKING SODA]; SORBITAN TRISTEARATE; LECITHIN (SOY); CONFECTIONER'S GLAZE; SALT; ARTIFICIAL FLAVOR; TAPIOCA DEXTRIN; CALCIUM CARBONATE",
        vegan: false,
        reviews: []
    },
    {
        _id: uuid.v4(),
        name: "York Peppermint Patties 175 Pieces",
        price: 16.99,
        stock: 126,
        rating: 4.8,
        numRatings: 167,
        image: "https://m.media-amazon.com/images/I/8186YoGBM-S._SX679_.jpg",
        manufacturer: "Henry Kessler",
        descrption: "Chill out with YORK dark chocolate peppermint patties candy with 70 percent less fat than other leading chocolate candy brands. These small but mighty candies invigorate your taste buds with a minty kick combined with rich dark chocolate to keep you feeling excited for a full day ahead. Bring a bulk box into work so everyone can have a piece and don't forget to keep a few for yourself. This box is perfect for any special occasion like movie marathons, birthday parties, work celebrations, family get-togethers and fundraising events as resale candy. Everyone can reach in and grab a YORK peppermint patties treats of their own. And with these bite-size sweets, they're a quick snack you can have on the go. The dark chocolate peppermint treats are also fun to bake with! Wrap your favorite cookie dough around the chocolate peppermint candy, bake in the oven, then experience a minty fresh cookie created by yours truly. You can also hand out scrumptious YORK dark chocolate peppermint patties candies during the holidays like in Easter baskets, Christmas stockings, Halloween candy bowls and Valentine's Day gift bags. These minty delights covered in dark chocolate are gluten-free and kosher for those who love a refreshing but rich snack.",
        ingredients: "SUGAR; CORN SYRUP; CHOCOLATE; COCOA; INVERT SUGAR; MILK FAT; EGG WHITES; LECITHIN (SOY); COCOA BUTTER; OIL OF PEPPERMINT; PGPR; NATURAL FLAVOR; MILK",
        vegan: false,
        reviews: []
    }
]

let exportedMethods = {
    bigness() {
        console.log(data.length);
        return data;
    }
}

module.exports = exportedMethods
